#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include "ecole.h"


//This function is used to enter full adresses

void SaisirAdresse(Adresse_t *A)
{
    printf("\nSaisir la rue : ");
    fgets(A->rue, RUEMAX, stdin);
    A->rue[strlen(A->rue)-1]='\0'; // we remove the new line character (\n) generated by the fgets() function

    printf("\nSaisir le code postal de la commune : ");
    scanf("%d", &A->CodePostal);
    getchar();

    printf("\nSaisir la ville : ");
    fgets(A->Ville, VILLEMAX, stdin);
    A->Ville[strlen(A->Ville)-1]='\0'; // we remove the new line character (\n) generated by the fgets() function
    printf("\nSaisir numero de telephone fixe:");
    fgets(A->TelMaison, TELMAX, stdin);
    A->TelMaison[strlen(A->TelMaison)-1]='\0'; // we remove the new line character (\n) generated by the fgets() function

    printf("\nSaisir numero de telephone mobile:");
    fgets(A->TelMobile, TELMAX, stdin);
    A->TelMobile[strlen(A->TelMobile)-1]='\0'; // we remove the new line character (\n) generated by the fgets() function

    printf("\nSaisir adresse mail : ");
    fgets(A->Mail, MAILMAX, stdin);
    A->Mail[strlen(A->Mail)-1]='\0'; // we remove the new line character (\n) generated by the fgets() function

}


// This function is used to display the school data, from a .cvs file which name is "fichier_ecole.csv"
void AfficherEcole(const char *nom_fichier, Ecole_t *Ec)
{

    //variables declaration to retrieve the data stored in the ".csv" file
    char ligne[LIGNE];    // temporary string to hold the files's lines (one after another))
    char *champ;        //


    FILE *ptr_fichierEcole; // a pointer is created to a FILE object

    ptr_fichierEcole=fopen("nom_fichier", "r"); // using the fopen() function with a "read" mode

    if(!ptr_fichierEcole) // in case of a problem
    {
        perror("erreur ouverture du fichier"); //the error message is displayed
        exit(EXIT_FAILURE); //the application is closed
    }
    else
    {

        fgets(ligne, LIGNE, ptr_fichierEcole);  // the line to be tokenized is read
        champ=strtok(ligne, ";");               // "champ" receive the first token, until the next ';' delimiter
        strcpy(Ec->nomEcole, champ);            // "champ" is put in its data place


        champ=strtok(NULL, ";");                // each following token is put into "champ"
        strcpy(Ec->nomDirecteur, champ);        // and then copied in its data place

        champ=strtok(NULL, ";");                // the above operation is repeated until the end of the line
        strcpy(Ec->prenomDirecteur, champ);

        champ=strtok(NULL, ";");                // the above operation is repeated until the end of the line
        Ec->nbclasse=atoi(champ);

        champ=strtok(NULL, ";");
        strcpy(Ec->AdresseEcole.rue, champ);

        champ=strtok(NULL, ";");
        Ec->AdresseEcole.CodePostal=atoi(champ);

        champ=strtok(NULL, ";");
        strcpy(Ec->AdresseEcole.Ville, champ);

        champ=strtok(NULL, ";");
        strcpy(Ec->AdresseEcole.TelMaison, champ);

        champ=strtok(NULL, ";");
        strcpy(Ec->AdresseEcole.TelMobile, champ);

        champ=strtok(NULL, ";");
        strcpy(Ec->AdresseEcole.Mail, champ);

    }

fclose(ptr_fichierEcole);                        // the ".csv" file is closed

//These are the display instructions of the school
printf("\tNom de l'Etablissement : %s\n", Ec->nomEcole);
printf("\tDirecteur de l'Etablissement: %s %s\n", Ec->nomDirecteur, Ec->prenomDirecteur);
printf("\t\n------ Adresse ------");
printf("\n\tRue: %s", Ec->AdresseEcole.rue);
printf("\n\tCode Postal et Commune: %d %s", Ec->AdresseEcole.CodePostal, Ec->AdresseEcole.Ville);
printf("\n\tTelephone Fixe: %s\n", Ec->AdresseEcole.TelMaison);
printf("\tTelephone Mobile: %s\n", Ec->AdresseEcole.TelMobile);
printf("\tAdresse mail: %s", Ec->AdresseEcole.Mail);
printf("\n\tNombre de classes: %s", Ec->nbclasse);
}


// This function is used to create/enter the school
void SaisirEcole(Ecole_t *Ec)
{
    printf("********** Saisie des informations Etablissement **********\n\n\n");

    printf("Saisir le nom de l'etablissement: ");
    fgets(Ec->nomEcole, NOMMAXECOLE, stdin);
    Ec->nomEcole[strlen(Ec->nomEcole)-1]='\0';              // we remove the new line character (\n) generated by the fgets() function

    printf("\nSaisir le nom du Directeur(trice): ");
    fgets(Ec->nomDirecteur, NOMMAX, stdin);
    Ec->nomDirecteur[strlen(Ec->nomDirecteur)-1]='\0';      // we remove the new line character (\n) generated by the fgets() function

    printf("\nSaisir le prenom du Directeur(trice): ");
    fgets(Ec->prenomDirecteur, PRENOMMAX, stdin);
    Ec->prenomDirecteur[strlen(Ec->prenomDirecteur)-1]='\0';// we remove the new line character (\n) generated by the fgets() function

    SaisirAdresse(&Ec->AdresseEcole);

    FILE *ptr_fichierEcole; // a pointer is created to a FILE object


    ptr_fichierEcole = fopen("fichier_ecole.csv", "w");     // using the fopen() function with a "write" mode

    if(!ptr_fichierEcole)                                   // in case of a problem
    {
        perror("erreur ouverture du fichier");              //the error message is displayed
        exit(EXIT_FAILURE);                                 //the application is closed
    }
    else
    {
        // the school's data are writen inside a '.cvs' file compatible LibreOffice/Microsoft Office
        fprintf(ptr_fichierEcole, "%s;%s;%s;%d;", Ec->nomEcole, Ec->nomDirecteur, Ec->prenomDirecteur, Ec->nbclasse);

        fprintf(ptr_fichierEcole, "%s ; %d ; %s ; %s ; %s ; %s", Ec->AdresseEcole.rue, Ec->AdresseEcole.CodePostal, Ec->AdresseEcole.Ville, Ec->AdresseEcole.TelMaison,
                                                                 Ec->AdresseEcole.TelMobile, Ec->AdresseEcole.Mail);
    }

fclose(ptr_fichierEcole);                                   // the '.csv' file is closed
}
